config/routes.rb
Changeons::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  namespace :api do
    namespace :v1 do
      resources :mailing_list_recipients, only: [:create]
      resources :links, only: [:index]
      resources :shares, only: [:index, :create]
      resources :users, only: [:show]
    end
  end

  root to: "links#index"
  #devise_for :users#, controllers: { registrations: 'users/registrations' }
end

app/views/shared/_comment_count.html.slim
javascript:
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = '#{ENV['DISQUS_SHORTNAME']}'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function () {
      var s = document.createElement('script'); s.async = true;
      s.type = 'text/javascript';
      s.src = '//' + disqus_shortname + '.disqus.com/count.js';
      (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
  }());

app/views/shared/_comments.html.slim
#disqus_thread
javascript:
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = "#{ENV['DISQUS_SHORTNAME']}"; // required: replace example with your forum shortname
  var disqus_identifier = "#{@link.disqus_uniq_identifier}";
  var disqus_title = "#{@link.name}";
  var disqus_url = "#{link_url @link}";
  var disqus_category_id = "#{Link.disqus_category_id}";


  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
noscript
  | Please enable JavaScript to view the
  a href="http://disqus.com/?ref_noscript"
    | comments powered by Disqus.
a.dsq-brlink href="http://disqus.com"
  | comments powered by
  span.logo-disqus
    | Disqus