config/routes.rb
Changeons::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  namespace :api do
    namespace :v1 do
      resources :mailing_list_recipients, only: [:create]
      resources :links, only: [:index]
      resources :shares, only: [:index, :create]
      resources :users, only: [:show]
    end
  end

  root to: "links#index"
  #devise_for :users#, controllers: { registrations: 'users/registrations' }
end

app/models/link.rb
class Link < Share
  belongs_to :category
  belongs_to :user

  LANGUAGES = ['FR', 'EN']
  validates :name, uniqueness: true, presence: true, length: { maximum: 160 }

  validates :url,
    uniqueness: true,
    presence: true,
    length: { maximum: 2000 },
    format: { with: URI.regexp(%w(http https)), message: :invalid_url_format }

  validates :language, presence: true, inclusion: { in: LANGUAGES }
  validates :category, presence: true

  def self.disqus_category_id
    ENV["DISQUS_LINK_ID"]
  end

  def disqus_uniq_identifier
    "#{Rails.env}_LINK_#{id}"
  end
end

app/controllers/api/v1/links_controller.rb
module Api
  module V1
    class LinksController < ApplicationController

      def index

        page = (params[:page] || 1).to_i
        links = Link.order(id: :desc)
        category = Category.where(name: params[:category]).first

        if category.present?
          links = links.where(category: category)
        end

        links = links.page(page).per(10)

        render json: links, each_serializer: LinkSerializer, meta: {total_pages: links.total_pages}
      end
    end
  end
end

app/controllers/web_api/links_controller.rb
class WebApi::LinksController < ApplicationController

  def index
    @links = Link.limit(15).order(created_at: :desc)
    @links = @links.where(category_id: params[:category]) if params[:category].present?
    render json: @links, each_serializer: LinkSerializer
  end

  def create
    @link = Link.new(create_params)

    if @link.save
      render json: @link
    else
      render json: { errors: @link.errors }, status: :unprocessable_entity
    end
  end

  private

  def create_params
    params.require(:link).permit(:name, :url, :category_id, :language, :user_id)
  end
end

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
    <tr>
      <td><%= link.name %></td>
      <td><%= link.url %></td>
      <td><%= link_to 'Show', link %></td>
      <td><%= link_to 'Edit', edit_link_path(link) %></td>
      <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Link', new_link_path %>